import {
  UserIcon,
  FileEditIcon,
  DocumentIcon,
  BarsIcon,
  BlogIcon,
  EmailIcon,
  PasswordIcon,
  HideEyeIcon,
  ShowEyeIcon,
  BellIcon,
  CrossMallIcon,
  LikeIcon,
  CommentIcon,
  ArrowUpIcon,
  YoutubeIcon,
  InstagramIcon,
  GithubIcon,
  WebsiteIcon,
  FacebookIcon,
  LikedIcon,
  TrashIcon,
  UsernameIcon,
  TwitterIcon,
} from "./icon";

export const ICONS = {
  user: UserIcon,
  edit: FileEditIcon,
  doc: DocumentIcon,
  bars: BarsIcon,
  blog: BlogIcon,
  email: EmailIcon,
  username: UsernameIcon,
  password: PasswordIcon,
  hideEyeIcon: HideEyeIcon,
  showEyeIcon: ShowEyeIcon,
  bellIcon: BellIcon,
  crossMallIcon: CrossMallIcon,
  trashIcon: TrashIcon,
  likeIcon: LikeIcon,
  likedIcon: LikedIcon,
  commentIcon: CommentIcon,
  arrowUpIcon: ArrowUpIcon,
};

export const SOCIAL_ICONS = {
  youtube: YoutubeIcon,
  instagram: InstagramIcon,
  github: GithubIcon,
  website: WebsiteIcon,
  facebook: FacebookIcon,
  twitter: TwitterIcon,
};
