
# POST http://localhost:3000/signin
# Content-Type: application/json 

# {
#     "email": "trntruongthanh@gmail.com",
#     "password": "Thanhkute0199hg"
# }


# POST http://localhost:3000/change-password
# Content-Type: application/json 
# Authorization: Bearer {access_token}

# {
#     "currentPassword": "Thanhtran123",
#     "newPassword": "Thanhkute0199"
# }



# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname": "Khoa Tran",
#     "email": "trnvankhoa1@gmail.com",
#     "password": "Trankhoa123"
# }



# GET http://localhost:3000/get-upload-url 



# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer {access_token}

# {
#     "title": "test title @ 3 134 # 4$",
#     "banner": "http://example.com/image-url",
#     "des": "this is a short",
#     "content": {
#         "blocks": [1, 2]
#     },
#     "tags": ["tags 1", "tags 2", "tags 3"]
# }


# GET  http://localhost:3000/latest-blogs
# GET  http://localhost:3000/trending-blogs


# POST http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#     "tag": "hoanghon"
# }


# POST http://localhost:3000/all-latest-blogs-count
# POST http://localhost:3000/search-blogs-count



# POST http://localhost:3000/search-users 
# Content-Type: application/json 

# {
#     "query": "trntruongthanh"
# }


# POST http://localhost:3000/get-profile
# Content-Type: application/json 

# {
#     "username": "trntruongthanh"
# }


# POST http://localhost:3000/get-blog
# Content-Type: application/json 

# {
#     "blog_id": "bien-A9jl5"
# }


//========================================================================================================

GET  http://localhost:3000/new-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDdhYWVmNDAxMTE1YmNkMmM3OWJhMCIsImlhdCI6MTc1NjQzNjU3Nn0.x4jVAPAF-FsGnZLyItqEWccBSH-tZsmT8fQD-nmkD1U

